platform :ios, '13.0'

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'FolioReaderKit', path: '../FolioReaderKit'
end

target 'quickread' do
  shared_pods
  pod 'Alamofire', '~> 4.5'
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AWSPluginsCore'
end
